# Hugo configuration for Hextra theme
baseURL = "https://lubenz007.github.io/"
languageCode = "en-us"
title = "BensiEgils"
theme = "hextra"

# Enable emoji in markdown
enableEmoji = true
# Enable Git info
enableGitInfo = true
# Enable robots.txt generation
enableRobotsTXT = true

# Pagination configuration
[pagination]
  pagerSize = 50

[params]
  description = "Documenting my journey with Azure, PowerShell, and automation"
  keywords = ["blog", "azure", "powershell", "automation", "security", "hextra"]
  
  # Theme configuration
  [params.theme]
    default = "system"      # light | dark | system
    displayToggle = true    # Show theme toggle button
  
  # Navbar configuration
  [params.navbar]
    displayTitle = true
    displayLogo = true
    width = "wide"
    [params.navbar.logo]
      path = "/assets/img/logo/BensiLogo.png"
  
  # Search configuration
  [params.search]
    enable = true
    type = "flexsearch"
  
  # Display settings
  displayUpdatedDate = true
  dateFormat = "January 2, 2006"
  
  # Blog configuration for Hextra theme
  [params.blog]
    [params.blog.list]
      displayTags = true
      pagerSize = 50
      sortBy = "date"
      sortOrder = "desc"
  
  # Footer
  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    pageRef = "/categories"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pageRef = "/tags"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = true
    noClasses = false
    style = "github"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false

[taxonomies]
  category = "categories"
  tag = "tags"

# Table of Contents configuration
[params.toc]
  displayTags = true

[permalinks]
  posts = "/posts/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]